### PR TITLE
Ankush Mallick - Files Uploaded

### PR DESCRIPTION
**Pull request by ankushmallick1100**

### CODE REVIEW

**Comment by ankushmallick1100** [comment]
Can you please meage it. It will very much helpful for me.

**Comment by parbati09** [comment]
@ankushmallick1100 please add problems where heap and hashmap data structures used...

**Comment by ankushmallick1100** [comment]
Can you please meage it. It will very much helpful for me.

**Comment by parbati09** [comment]
@ankushmallick1100 do not do it on c code...because here you cannot use priority_queue and unordered_map like data structures..

**Comment by parbati09** [comment]
please try to code it on c++/java/python

**Comment by parbati09** [comment]
I'm merging it for now..

**Comment by parbati09** [comment]
please mark a star for this repo..thank you

**Comment by ankushmallick1100** [comment]
> please mark a star for this repo..thank you

sure. Thanks @parbati09 .

**Pull request merged**
